/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.libreria.gral.system.ui;

import com.mycompany.libreria.gral.system.controller.GestorLibreriaGralSystem;
import com.mycompany.libreria.gral.system.model.Codigo;
import com.mycompany.libreria.gral.system.model.Inventario;
import com.mycompany.libreria.gral.system.model.Oferta;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import utiles.Clave;
import utiles.Mensaje;
import utiles.Utiles;

/**
 *
 * @author KEVIN
 */
public class FAltaInventario extends javax.swing.JFrame {

    private GestorLibreriaGralSystem gestor;
    private MainFrame mainFrame;
    private boolean bandCerrar;

    private StringBuffer codigoBusqCamp;
    private StringBuffer codigoBusqSP;
    private StringBuffer codigoBusqOtro;
    private String codigo;
    private String codigoLote;
    private String descripcion;
    private int stock;
    private BigDecimal costoUnit;
    private BigDecimal precioVenta;
    private int unidOfert;
    private Date fechaIng;
    private List<Oferta> lOfertas;
    private List<Codigo> lCodigo;
    private boolean estadoSeguro;

    /**
     * Creates new form FrameAlta
     */
    public FAltaInventario(MainFrame mainFrame, GestorLibreriaGralSystem gestor) {
        initComponents();
        this.mainFrame = mainFrame;
        this.gestor = gestor;
        this.bandCerrar = false;

        this.reiniciarValoresLogicos();
        this.limpiarFormulario();
        this.iniciarFormulario();
    }

    public FAltaInventario(MainFrame mainFrame, GestorLibreriaGralSystem gestor, String value) {
        initComponents();
        this.mainFrame = mainFrame;
        this.gestor = gestor;
        this.bandCerrar = true;

        this.reiniciarValoresLogicos();
        this.limpiarFormulario();
        this.cargarValoresExtra(value);
        this.iniciarFormulario();
    }
    
    public FAltaInventario(MainFrame mainFrame, GestorLibreriaGralSystem gestor,
            String codigo, String descripcion, String precioCosto) {
        initComponents();
        this.mainFrame = mainFrame;
        this.gestor = gestor;
        this.bandCerrar = true;

        this.reiniciarValoresLogicos();
        this.limpiarFormulario();
        this.cargarValoresExtra(codigo, descripcion, precioCosto);
        this.iniciarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnTI = new javax.swing.JButton();
        btnCP = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        edtDescripcion = new javax.swing.JTextField();
        edtCodigo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        edtCodigoLote = new javax.swing.JTextField();
        btnMasCod = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        edtCostoUnitario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        edtStock = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        edtUnidOf = new javax.swing.JTextField();
        edtPrecioVenta = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnLOfertas = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        edtFechaIngreso = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cbEstSeguro = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnImpCod = new javax.swing.JButton();
        menuBarra = new javax.swing.JMenuBar();
        mCerrar = new javax.swing.JMenu();
        mItemCerrar = new javax.swing.JMenuItem();
        mConsultar = new javax.swing.JMenu();
        mItemCodBusq = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta Inventario");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnTI.setText("Tomar una instantánea");

        btnCP.setText("Cargar desde el PC");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Imagen :");

        jLabel1.setText("...ruta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCP, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnTI, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCP)
                    .addComponent(btnTI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Código de Lote :");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        edtDescripcion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtDescripcionKeyTyped(evt);
            }
        });

        edtCodigo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        edtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtCodigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtCodigoFocusLost(evt);
            }
        });
        edtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtCodigoKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Código :");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Descripción :");

        edtCodigoLote.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtCodigoLote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtCodigoLoteKeyTyped(evt);
            }
        });

        btnMasCod.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMasCod.setText("+");
        btnMasCod.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMasCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasCodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btnMasCod)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel17)
                        .addGap(2, 2, 2)
                        .addComponent(edtCodigoLote, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtCodigoLote)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnMasCod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edtDescripcion)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        edtCostoUnitario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtCostoUnitario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        edtCostoUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtCostoUnitarioKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Stock:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Costo unit. :");

        edtStock.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtStock.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        edtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtStockKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(53, 53, 53)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edtCostoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(edtCostoUnitario)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        edtUnidOf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtUnidOf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        edtUnidOf.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        edtUnidOf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtUnidOfKeyTyped(evt);
            }
        });

        edtPrecioVenta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtPrecioVenta.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        edtPrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtPrecioVentaKeyTyped(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Unid. ofertadas :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Precio unit. :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("*");

        btnLOfertas.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnLOfertas.setText("+");
        btnLOfertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLOfertasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edtUnidOf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addComponent(btnLOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edtPrecioVenta)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtUnidOf))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        edtFechaIngreso.setEditable(false);
        edtFechaIngreso.setBackground(new java.awt.Color(255, 255, 255));
        edtFechaIngreso.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtFechaIngreso.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Fecha de ingreso:");
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        cbEstSeguro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbEstSeguro.setText("E.S.");
        cbEstSeguro.setIconTextGap(8);
        cbEstSeguro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbEstSeguroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbEstSeguro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(edtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cbEstSeguro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnImpCod.setText("Imp. cod.");
        btnImpCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpCodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImpCod)
                .addGap(193, 193, 193)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImpCod))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mCerrar.setText("Archivo");

        mItemCerrar.setText("Cerrar");
        mItemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemCerrarActionPerformed(evt);
            }
        });
        mCerrar.add(mItemCerrar);

        menuBarra.add(mCerrar);

        mConsultar.setText("Editar");

        mItemCodBusq.setText("Código de Busqueda");
        mItemCodBusq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemCodBusqActionPerformed(evt);
            }
        });
        mConsultar.add(mItemCodBusq);

        menuBarra.add(mConsultar);

        setJMenuBar(menuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtStockKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        if (car >= '0' & car <= '9') {
            // Hacer nada.
        } else {
            evt.consume();
        }
        
        Utiles.suprimirComilla(edtStock);
    }//GEN-LAST:event_edtStockKeyTyped

    private void edtCostoUnitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCostoUnitarioKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        if (car >= '0' && car <= '9') {
            // Hacer nada.
        } else {
            if (car == '.') {
                try {
                    String value = edtCostoUnitario.getText();

                    if (value.contains(".")) {
                        evt.consume();
                    }
                } catch (Exception e) {
                    edtCostoUnitario.setText("");
                    evt.consume();
                }
            } else {
                evt.consume();
            }
        }
        
        Utiles.suprimirComilla(edtCostoUnitario);
    }//GEN-LAST:event_edtCostoUnitarioKeyTyped

    private void edtPrecioVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtPrecioVentaKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        if (car >= '0' && car <= '9') {
            // Hacer nada.
        } else {
            if (car == '.') {
                try {
                    String value = edtPrecioVenta.getText();

                    if (value.contains(".")) {
                        evt.consume();
                    }
                } catch (Exception e) {
                    edtPrecioVenta.setText("");
                    evt.consume();
                }
            } else
            {
                evt.consume();
            }
        }
        
        Utiles.suprimirComilla(edtPrecioVenta);
    }//GEN-LAST:event_edtPrecioVentaKeyTyped

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        iniciarProc3();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        Clave result;

        //  Validaciones
        try {
            result = iniciarProc2();
        } catch (Exception e) {
            e.printStackTrace();
            result = Clave.RESULT_ERROR;
        }

        switch (result) {
            case RESULT_ERROR: {
                Mensaje.mostrarMensaje5(rootPane);
                this.dispose();
                break;
            }
            case RESULT_ERROR_BD: {
                Mensaje.mostrarMensaje3(rootPane);
                this.dispose();
                break;
            }
            case RESULT_ERROR_CAMPOS_INVALIDOS:
            {
                Mensaje.mostrarMensaje2(rootPane);
                break;
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
        this.edtCodigo.transferFocus();
    }//GEN-LAST:event_formWindowDeactivated

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void edtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoKeyTyped
        // TODO add your handling code here:

        // Validaciones
        int comilla = 39;

        if (evt.getKeyChar() == comilla) {
            evt.consume();
        }
        
        Utiles.suprimirComilla(edtCodigo);
    }//GEN-LAST:event_edtCodigoKeyTyped

    private void btnImpCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpCodActionPerformed
        // TODO add your handling code here:
        String cod = Utiles.obtenerValor(edtCodigo);

        if (cod.isEmpty()) {
            Mensaje.mostrarMensajeImp(this);
        } else {
            mainFrame.iniciarProc23(cod);
            Mensaje.mostrarMensaje27(rootPane);
        }
    }//GEN-LAST:event_btnImpCodActionPerformed

    private void edtUnidOfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtUnidOfKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        if (car >= '0' & car <= '9') {
            // Hacer nada.
        } else {
            evt.consume();
        }
        
        Utiles.suprimirComilla(edtUnidOf);
    }//GEN-LAST:event_edtUnidOfKeyTyped

    private void btnLOfertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLOfertasActionPerformed
        // TODO add your handling code here:

        FOfertasAI formOfertas = new FOfertasAI(codigo, lOfertas);

        formOfertas.setVisible(true);
    }//GEN-LAST:event_btnLOfertasActionPerformed

    private void edtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        Clave result = Clave.RESULT_SIN_DEFINIR;
        
        if (key == KeyEvent.VK_ENTER) {
            String cod = Utiles.obtenerValor(edtCodigo);

            if (cod == null || cod.isEmpty())
            {
                result = Clave.RESULT_CAMPO_BLANCO;
            } else
            {                
                try {
                    result = iniciarProc1(cod);
                } catch (Exception e) {
                    e.printStackTrace();
                    result = Clave.RESULT_ERROR;
                }
                
                switch(result)
                {
                    case RESULT_ERROR:
                    {
                        Mensaje.mostrarMensaje5(rootPane);
                        break;
                    }
                    case RESULT_ERROR_BD:
                    {
                        Mensaje.mostrarMensaje3(rootPane);
                        break;
                    }
                    case RESULT_OK:
                    {
                        // Hacer nada.
                        break;
                    }
                    case RESULT_CAMPO_BLANCO:
                    {                        
                        break;
                    }
                }
            }
        }
    }//GEN-LAST:event_edtCodigoKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void edtCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCodigoFocusGained
        // TODO add your handling code here:
        Utiles.establecerFocusActivoG(edtCodigo);
    }//GEN-LAST:event_edtCodigoFocusGained

    private void mItemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mItemCerrarActionPerformed

    private void mItemCodBusqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemCodBusqActionPerformed
        // TODO add your handling code here:
        FCodigoBusqueda form = new FCodigoBusqueda(codigoBusqCamp, codigoBusqSP, codigoBusqOtro, true);
        
        form.setVisible(true);
        this.cbEstSeguro.setSelected(false);
    }//GEN-LAST:event_mItemCodBusqActionPerformed

    private void edtCodigoLoteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoLoteKeyTyped
        // TODO add your handling code here:
        Utiles.suprimirComilla(evt);
        Utiles.suprimirComilla(edtCodigoLote);
    }//GEN-LAST:event_edtCodigoLoteKeyTyped

    private void edtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtDescripcionKeyTyped
        // TODO add your handling code here:
        Utiles.suprimirComilla(evt);
        Utiles.suprimirComilla(edtDescripcion);
    }//GEN-LAST:event_edtDescripcionKeyTyped

    private void edtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCodigoFocusLost
        // TODO add your handling code here:
        Utiles.establecerFocusInactivo(edtCodigo);
    }//GEN-LAST:event_edtCodigoFocusLost

    private void btnMasCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasCodActionPerformed
        // TODO add your handling code here:
        FCodigo form = new FCodigo(gestor, lCodigo, codigo, Clave.MENSAJE_NUEVO_INVENTARIO, this);
        
        form.setVisible(true);
    }//GEN-LAST:event_btnMasCodActionPerformed

    private void cbEstSeguroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbEstSeguroMouseClicked
        // TODO add your handling code here
        
        if (codigoBusqCamp.toString().trim().isEmpty()
                & codigoBusqSP.toString().trim().isEmpty()
                & codigoBusqOtro.toString().trim().isEmpty())
        {
            this.cbEstSeguro.setSelected(false);
        }
    }//GEN-LAST:event_cbEstSeguroMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCP;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImpCod;
    private javax.swing.JButton btnLOfertas;
    private javax.swing.JButton btnMasCod;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnTI;
    private javax.swing.JCheckBox cbEstSeguro;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JTextField edtCodigoLote;
    private javax.swing.JTextField edtCostoUnitario;
    private javax.swing.JTextField edtDescripcion;
    private javax.swing.JTextField edtFechaIngreso;
    private javax.swing.JTextField edtPrecioVenta;
    private javax.swing.JTextField edtStock;
    private javax.swing.JTextField edtUnidOf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JMenu mCerrar;
    private javax.swing.JMenu mConsultar;
    private javax.swing.JMenuItem mItemCerrar;
    private javax.swing.JMenuItem mItemCodBusq;
    private javax.swing.JMenuBar menuBarra;
    // End of variables declaration//GEN-END:variables

    //*************************** Formulario ***********************************************
    /**
     * Limipieza
     */
    private void limpiarFormulario() {
        Utiles.limpiarCampo(edtCodigo);
        limpiarCamposDeTexto();
        Utiles.descolorear(btnMasCod);
        this.cbEstSeguro.setSelected(false);        
    }

    private void limpiarCamposDeTexto() {
        this.edtCodigo.setText("");
        this.edtCodigoLote.setText("");
        this.edtDescripcion.setText("");
        this.edtStock.setText("");
        this.edtCostoUnitario.setText("");
        this.edtPrecioVenta.setText("");
        this.edtUnidOf.setText("");
        this.edtFechaIngreso.setText("");
    }

   /**
    * Configuraciones
    */
    
    private void iniciarFormulario() {
        edtCodigo.setEnabled(true);
        Utiles.requerirFocus(edtCodigo);
        deshabilitarComponentes();
    }

    private void inicializarComponentes() {

        this.codigo = Utiles.obtenerValor(edtCodigo);
        this.edtUnidOf.setText("1");
        this.edtStock.setText("1");
        this.edtFechaIngreso.setText(Utiles.toStringM3(fechaIng));
        
        if (edtCostoUnitario.getText().trim().isEmpty())
        {
           this.edtCostoUnitario.setText("0.00"); 
        }else
        {
            // Hacer nada.
        }
    }

    private void reiniciarValoresLogicos() {

        codigoBusqCamp = new StringBuffer();
        codigoBusqSP = new StringBuffer();
        codigoBusqOtro = new StringBuffer();
        codigo = "";
        codigoLote = "";
        descripcion = "";
        stock = 0;
        costoUnit = new BigDecimal(0);
        precioVenta = new BigDecimal(0);
        unidOfert = 0;
        fechaIng = Calendar.getInstance().getTime();;
        lOfertas = new ArrayList<>();
        lCodigo = new ArrayList<>();
        estadoSeguro = false;
    }

    private void deshabilitarComponentes() {
        boolean band = false;

        edtCodigoLote.setEnabled(band);
        edtDescripcion.setEnabled(band);
        edtStock.setEnabled(band);
        edtCostoUnitario.setEnabled(band);
        edtPrecioVenta.setEnabled(band);
        edtUnidOf.setEnabled(band);
        btnCP.setEnabled(band);
        btnTI.setEnabled(band);
        btnImpCod.setEnabled(band);
        btnGuardar.setEnabled(band);
        btnLOfertas.setEnabled(band);
        mItemCodBusq.setEnabled(band);
        btnMasCod.setEnabled(band);
        cbEstSeguro.setEnabled(band);
    }

    private void habilitarComponentes() {
        boolean band = true;

        edtCodigoLote.setEnabled(band);
        edtDescripcion.setEnabled(band);
        edtStock.setEnabled(band);
        edtCostoUnitario.setEnabled(band);
        edtPrecioVenta.setEnabled(band);
        edtUnidOf.setEnabled(band);
        btnCP.setEnabled(band);
        btnTI.setEnabled(band);
        btnImpCod.setEnabled(band);
        btnLOfertas.setEnabled(band);
        btnGuardar.setEnabled(band);
        btnMasCod.setEnabled(band);
        mItemCodBusq.setEnabled(band);
        cbEstSeguro.setEnabled(band);
    }

    public void actualizar()
    {
        if (lCodigo.isEmpty())
        {
            Utiles.descolorear(btnMasCod);
        } else
        {
            Utiles.colorearRojo(btnMasCod);
        }
    }
    
    //************************** Procedimientos *******************************************
    
    private Clave iniciarProc1(String cod) {
        Clave result = Clave.RESULT_OK;

        try {
            if (gestor.consultarInvPorCodigo(cod)) {
                Mensaje.mostrarMensajeExisteProducto(this);
                Utiles.establecerFocus2(edtCodigo);
                Utiles.requerirFocus(edtCodigo);
                
                FConsultaInventario form = new FConsultaInventario();
                
                form.cargarInventario(gestor.obtenerInvPorCodigoM2(cod));
                form.mostrarInformacion();
                form.setVisible(true);
                
            } else {
                Utiles.deshabilitarCampo(edtCodigo);
                Utiles.establecerFocus1(edtCodigo);
                habilitarComponentes();
                inicializarComponentes();                
                Utiles.requerirFocus(edtPrecioVenta);
            }
        } catch (Exception e) {
            e.printStackTrace();
            return Clave.RESULT_ERROR_BD;
        }

        return result;
    }

    private Clave iniciarProc2() {
        Clave result = Clave.RESULT_OK;
        
        if (existenCamposBlancos() || existenCamposNoHomogeneos()) {
            return result = Clave.RESULT_ERROR_CAMPOS_INVALIDOS;
        }

        codigo = Utiles.obtenerValor(edtCodigo);
        codigoLote = edtCodigoLote.getText().trim();
        descripcion = edtDescripcion.getText().trim();
        stock = new Integer(edtStock.getText().trim());
        costoUnit = new BigDecimal(edtCostoUnitario.getText().trim());
        fechaIng = Calendar.getInstance().getTime();
        precioVenta = new BigDecimal(edtPrecioVenta.getText().trim());
        unidOfert = new Integer(edtUnidOf.getText().trim());
        
        if (codigoBusqCamp.toString().trim().isEmpty()
                & codigoBusqSP.toString().trim().isEmpty()
                & codigoBusqOtro.toString().trim().isEmpty())
        {
            estadoSeguro = false;
        } else
        {
            if (cbEstSeguro.isSelected())
            {
                estadoSeguro = true;
            } else
            {
                estadoSeguro = false;
            }
        }
        
        try {
            gestor.guardarInvNuevo(codigo, codigoLote,
                    codigoBusqCamp.toString().trim(),
                    codigoBusqSP.toString().trim(),
                    codigoBusqOtro.toString().trim(),
                    descripcion, stock,
                costoUnit, lOfertas, precioVenta, unidOfert, lCodigo, estadoSeguro);
        } catch (Exception e) {
            e.printStackTrace();
            return result = Clave.RESULT_ERROR_BD;
        }
        
        try {
            Inventario inv = gestor.obtenerInvPorCodigoM2(codigo);
            
            gestor.guardarEntNueva(inv);
        } catch (Exception e) {
            e.printStackTrace();
            return result = Clave.RESULT_ERROR_BD;
        }
        
        JOptionPane.showMessageDialog(rootPane, "Inventario guardado exitosamente!!");

        if (bandCerrar) {
            this.dispose();
        } else {
            iniciarProc3();
        }

        try {
            mainFrame.actualizar();
        } catch (Exception e) {
        }     

        return result;
    }
    
    private void iniciarProc3()
    {
        limpiarFormulario();
        reiniciarValoresLogicos();
        iniciarFormulario();
    }
    
    private boolean existenCamposBlancos() {
        boolean bandera = false;
        String codigo = this.edtCodigo.getText();
        String descripcion = this.edtDescripcion.getText();
        String cantEnt = this.edtStock.getText();
        String precioCosto = this.edtCostoUnitario.getText();
        String precioVenta = this.edtPrecioVenta.getText();
        String undOfer = this.edtUnidOf.getText();

        if (codigo == null || codigo.trim().isEmpty()) {
            bandera = true;
        }
        if (descripcion == null || descripcion.trim().isEmpty()) {
            bandera = true;
        }
        if (cantEnt == null || cantEnt.trim().isEmpty()) {
            bandera = true;
        }
        if (precioCosto == null || precioCosto.trim().isEmpty()) {
            bandera = true;
        }
        if (precioVenta == null || precioVenta.trim().isEmpty()) {
            bandera = true;
        }
        if (undOfer == null || undOfer.trim().isEmpty()) {
            bandera = true;
        }

        return bandera;
    }

    private boolean existenCamposNoHomogeneos() {
        boolean bandera = false;

        try {
            int value = new Integer(this.edtStock.getText());
            
            if (value < 0) {
                bandera = true;
            }
        } catch (Exception e) {
            bandera = true;
        }

        try {
            int value = new Integer(this.edtUnidOf.getText());
            
            if (value < 1) {
                bandera = true;
            }
        } catch (Exception e) {
            bandera = true;
        }

        try {
            BigDecimal value1 = new BigDecimal(this.edtCostoUnitario.getText());
            BigDecimal value2 = new BigDecimal(this.edtPrecioVenta.getText());
              
            if (value1.doubleValue() < 0 || value2.doubleValue() < 0) {
                bandera = true;
            }
            
            if (value1.doubleValue() >= value2.doubleValue()) {
                bandera = true;
            }
        } catch (Exception e) {
            bandera = true;
        }
        
        return bandera;
    }

    private void cargarValoresExtra(String value) {
        this.edtCodigo.setText(value);
    }
    
    private void cargarValoresExtra(String codigo, String descripcion, String precoCosto) {
        codigoBusqCamp.append(codigo);
        edtDescripcion.setText(descripcion);
        edtCostoUnitario.setText(precoCosto);
    }
}
