/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.libreria.gral.system.ui;

import java.awt.event.KeyEvent;
import utiles.Utiles;

/**
 *
 * @author Kevin
 */
public class FCodigoBusqueda extends javax.swing.JFrame {

    private StringBuffer codBusq1;
    private StringBuffer codBusq2;
    private StringBuffer codBusq3;
    private boolean band;

    /**
     * Creates new form FConsultaInventario
     */
    public FCodigoBusqueda(StringBuffer codBusq1, StringBuffer codBusq2, StringBuffer codBusq3, boolean band) {
        initComponents();
        this.codBusq1 = codBusq1;
        this.codBusq2 = codBusq2;
        this.codBusq3 = codBusq3;
        this.band = band;
        limpiarFormulario();
        iniciarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        edtCampeon = new javax.swing.JTextField();
        edtSP = new javax.swing.JTextField();
        edtOtro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Información de inventario");
        setAlwaysOnTop(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Detalles:");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        btnCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCancelarKeyPressed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        edtCampeon.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtCampeon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtCampeonKeyTyped(evt);
            }
        });

        edtSP.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtSPKeyTyped(evt);
            }
        });

        edtOtro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtOtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtOtroKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Código de búsqueda (CAMPEON) :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Código de búsqueda (OTRO) :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Código de búsqueda (SAN PABLO) :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(edtOtro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                        .addComponent(edtSP, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(edtCampeon, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtCampeon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtSP, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtOtro, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCancelarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarKeyPressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            iniciarProc1();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void edtCampeonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCampeonKeyTyped
        // TODO add your handling code here:
        Utiles.suprimirComilla(evt);
        Utiles.suprimirComilla(edtCampeon);
    }//GEN-LAST:event_edtCampeonKeyTyped

    private void edtSPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtSPKeyTyped
        // TODO add your handling code here:
        Utiles.suprimirComilla(evt);
        Utiles.suprimirComilla(edtSP);
    }//GEN-LAST:event_edtSPKeyTyped

    private void edtOtroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtOtroKeyTyped
        // TODO add your handling code here:
        Utiles.suprimirComilla(evt);
        Utiles.suprimirComilla(edtOtro);
    }//GEN-LAST:event_edtOtroKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField edtCampeon;
    private javax.swing.JTextField edtOtro;
    private javax.swing.JTextField edtSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    //************************ Formulario ************************************
    private void limpiarFormulario() {
        edtCampeon.setText("");
        edtSP.setText("");
        edtOtro.setText("");
    }

    public void mostrarInformacion() {
       edtCampeon.setText(codBusq1.toString());
        edtSP.setText(codBusq2.toString());
        edtOtro.setText(codBusq3.toString());
    }

    private void iniciarFormulario() {
        
        this.btnGuardar.requestFocus();
        habilitarComponentes();
        mostrarInformacion();
    }

    private void habilitarComponentes()
    {
        edtCampeon.setEditable(band);
        edtSP.setEditable(band);
        edtOtro.setEditable(band);
    }
    //************************ Procedimientos *****************************
    public void iniciarProc1() {
        String valueCampeon = Utiles.obtenerValor(edtCampeon);
        String valueSP = Utiles.obtenerValor(edtSP);
        String valueOtro = Utiles.obtenerValor(edtOtro);
        
        codBusq1.delete(0, codBusq1.length());
        codBusq1.append(valueCampeon);
        
        codBusq2.delete(0, codBusq2.length());
        codBusq2.append(valueSP);
        
        codBusq3.delete(0, codBusq3.length());
        codBusq3.append(valueOtro);
        
        this.dispose();
    }

}
