/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.libreria.gral.system.ui;

import com.mycompany.libreria.gral.system.controller.GestorLibreriaGralSystem;
import com.mycompany.libreria.gral.system.model.Inventario;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import utiles.Clave;
import utiles.Mensaje;
import utiles.Utiles;

/**
 *
 * @author KEVIN
 */
public class FEntrada extends javax.swing.JFrame {

    private GestorLibreriaGralSystem gestor;
    private MainFrame mainFrame;
    private boolean bandCerrar;

    private String codigo;
    private String codigoLote;
    private String descripcion;
    private int cantEntrada;
    private BigDecimal costoUnit;
    private BigDecimal precioVenta;
    private int unidOfert;
    private Inventario inv;

    /**
     * Creates new form FrameAlta
     */
    public FEntrada(MainFrame mainFrame, GestorLibreriaGralSystem gestor) {
        initComponents();
        this.mainFrame = mainFrame;
        this.gestor = gestor;
        this.bandCerrar = false;

        this.reiniciarValoresLogicos();
        this.limpiarFormulario();
        this.iniciarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        edtDescripcion = new javax.swing.JTextField();
        edtCodigo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        edtCodigoLote = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        edtCostoUnitario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        edtCantEnt = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        edtUnidOf = new javax.swing.JTextField();
        edtPrecioVenta = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnImpCod = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnTI = new javax.swing.JButton();
        btnCP = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entradas");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Código de Lote :");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        edtDescripcion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtDescripcionKeyTyped(evt);
            }
        });

        edtCodigo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        edtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtCodigoFocusGained(evt);
            }
        });
        edtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtCodigoKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Código :");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Descripción :");

        edtCodigoLote.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtCodigoLote.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        edtCodigoLote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtCodigoLoteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edtCodigoLote, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtCodigoLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        edtCostoUnitario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtCostoUnitario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        edtCostoUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtCostoUnitarioKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Cant. de entrada: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Costo unit. :");

        edtCantEnt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtCantEnt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        edtCantEnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtCantEntKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edtCantEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edtCostoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtCantEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtCostoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        edtUnidOf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtUnidOf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        edtUnidOf.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        edtUnidOf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtUnidOfKeyTyped(evt);
            }
        });

        edtPrecioVenta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtPrecioVenta.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        edtPrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtPrecioVentaKeyTyped(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Unid. ofertadas :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Precio unit. :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("*");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edtUnidOf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtPrecioVenta)
                    .addComponent(edtUnidOf))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnImpCod.setText("Imp. cod.");
        btnImpCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpCodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImpCod)
                .addGap(193, 193, 193)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImpCod))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnTI.setText("Tomar una instantánea");

        btnCP.setText("Cargar desde el PC");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Imagen :");

        jLabel1.setText("...ruta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCP, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnTI, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCP)
                    .addComponent(btnTI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtCantEntKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCantEntKeyTyped
        // TODO add your handling code here:

        char car = evt.getKeyChar();

        if (car >= '0' & car <= '9') {
            // Hacer nada.
        } else {
            evt.consume();
        }
        
        Utiles.suprimirComilla(edtCantEnt);
    }//GEN-LAST:event_edtCantEntKeyTyped

    private void edtCostoUnitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCostoUnitarioKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        if (car >= '0' && car <= '9') {
            // Hacer nada.
        } else {
            if (car == '.') {
                try {
                    String value = edtCostoUnitario.getText();

                    if (value.contains(".")) {
                        evt.consume();
                    }
                } catch (Exception e) {
                    edtCostoUnitario.setText("");
                    evt.consume();
                }
            } else {
                evt.consume();
            }
        }
        
        Utiles.suprimirComilla(edtCostoUnitario);
    }//GEN-LAST:event_edtCostoUnitarioKeyTyped

    private void edtPrecioVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtPrecioVentaKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        if (car >= '0' && car <= '9') {
            // Hacer nada.
        } else {
            if (car == '.') {
                try {
                    String value = edtPrecioVenta.getText();

                    if (value.contains(".")) {
                        evt.consume();
                    }
                } catch (Exception e) {
                    edtPrecioVenta.setText("");
                    evt.consume();
                }
            } else {
                evt.consume();
            }
        }
        
        Utiles.suprimirComilla(edtPrecioVenta);
    }//GEN-LAST:event_edtPrecioVentaKeyTyped

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
        reiniciarValoresLogicos();
        iniciarFormulario();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        Clave result;

        try {
            result = iniciarProc2();
        } catch (Exception e) {
            e.printStackTrace();
            result = Clave.RESULT_ERROR;
        }

        switch (result) {
            case RESULT_ERROR: {
                Mensaje.mostrarMensaje5(rootPane);
                dispose();
                break;
            }
            case RESULT_ERROR_CAMPOS_INVALIDOS: {
                Mensaje.mostrarMensaje2(this);
                break;
            }
            case RESULT_ERROR_BD: {
                Mensaje.mostrarMensaje3(this);
                dispose();
                break;
            }
            case RESULT_OK: {

                Mensaje.mostrarMensaje18(rootPane);
                try {
                    mainFrame.actualizar();
                } catch (Exception e) {
                }
                

                if (bandCerrar) {
                    this.dispose();
                } else {
                    this.limpiarFormulario();
                    this.iniciarFormulario();
                }

                break;
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
        this.edtCodigo.transferFocus();
    }//GEN-LAST:event_formWindowDeactivated

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void edtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoKeyTyped
        // TODO add your handling code here:

        // Validaciones
        int comilla = 39;

        if (evt.getKeyChar() == comilla) {
            evt.consume();
        }
        
        Utiles.suprimirComilla(edtCodigo);
    }//GEN-LAST:event_edtCodigoKeyTyped

    private void btnImpCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpCodActionPerformed
        // TODO add your handling code here:
        if (mainFrame != null) {
            String cod = null;

            try {
                cod = edtCodigo.getText().trim();
            } catch (Exception e) {
            }

            if (cod == null || cod.isEmpty()) {
                Mensaje.mostrarMensajeImp(this);
            } else {

                mainFrame.iniciarProc23(cod);
                JOptionPane.showMessageDialog(this, "Agregado a la lista de impresión!");
            }
        }
    }//GEN-LAST:event_btnImpCodActionPerformed

    private void edtUnidOfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtUnidOfKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        if (car >= '0' & car <= '9') {
            // Hacer nada.
        } else {
            evt.consume();
        }
        
        Utiles.suprimirComilla(edtUnidOf);
    }//GEN-LAST:event_edtUnidOfKeyTyped

    private void edtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Clave result;

            try {
                result = iniciarProc1();
            } catch (Exception e) {
                e.printStackTrace();
                result = Clave.RESULT_ERROR;
            }

            switch (result) {
                case RESULT_ERROR_BD: {
                    Mensaje.mostrarMensaje3(rootPane);
                    break;
                }
                case RESULT_ERROR:
                {
                    Mensaje.mostrarMensaje5(rootPane);
                    break;
                }
            }
        }
    }//GEN-LAST:event_edtCodigoKeyPressed

    private void edtCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCodigoFocusGained
        // TODO add your handling code here:
        Utiles.requerirFocus(edtCodigo);
    }//GEN-LAST:event_edtCodigoFocusGained

    private void edtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtDescripcionKeyTyped
        // TODO add your handling code here:
        Utiles.suprimirComilla(edtDescripcion);
    }//GEN-LAST:event_edtDescripcionKeyTyped

    private void edtCodigoLoteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoLoteKeyTyped
        // TODO add your handling code here:
        Utiles.suprimirComilla(edtCodigoLote);
    }//GEN-LAST:event_edtCodigoLoteKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCP;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImpCod;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnTI;
    private javax.swing.JTextField edtCantEnt;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JTextField edtCodigoLote;
    private javax.swing.JTextField edtCostoUnitario;
    private javax.swing.JTextField edtDescripcion;
    private javax.swing.JTextField edtPrecioVenta;
    private javax.swing.JTextField edtUnidOf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
    
    //***************************** Formulario *******************************************
    
    /**
     * Limpieza de componentes
     */
    
    private void limpiarFormulario() {
        limpiarCamposDeTexto();
        Utiles.limpiarCampo(edtCodigo);
    }

    private void limpiarCamposDeTexto() {
        this.edtCodigo.setText("");
        this.edtCodigoLote.setText("");
        this.edtDescripcion.setText("");
        this.edtCantEnt.setText("");
        this.edtCostoUnitario.setText("");
        this.edtPrecioVenta.setText("");
        this.edtUnidOf.setText("");
    }

    private void reiniciarValoresLogicos() {
        
        codigo = "";
        codigoLote = "";
        descripcion = "";
        cantEntrada = 0;
        costoUnit = new BigDecimal(0);
        precioVenta = new BigDecimal(0);
        unidOfert = 0;
        inv = null;
    }
    
    private void inicializarComponentes() {

        codigo = inv.getProducto().getCodigo();
        codigoLote = inv.getProducto().getCodigoLote();
        descripcion = inv.getProducto().getDescripcion();
        cantEntrada = 0;
        costoUnit = inv.getCostoUnitario();        
        unidOfert = inv.getUnidOf();
        precioVenta = inv.getpVenta();
        
        // Campos
        edtCodigoLote.setText(codigoLote);
        edtDescripcion.setText(descripcion);
        edtCantEnt.setText(String.valueOf(cantEntrada));
        edtCostoUnitario.setText(String.valueOf(costoUnit));
        edtUnidOf.setText(String.valueOf(unidOfert));
        edtPrecioVenta.setText(String.valueOf(precioVenta));
    }

    private void iniciarFormulario() {
        edtCodigo.setEnabled(true);
        deshabilitarComponentes();
        Utiles.requerirFocus(edtCodigo);
    }

    private void deshabilitarComponentes() {
        boolean band = false;

        edtCodigoLote.setEnabled(band);
        edtDescripcion.setEnabled(band);
        edtCantEnt.setEnabled(band);
        edtCostoUnitario.setEnabled(band);
        edtPrecioVenta.setEnabled(band);
        edtUnidOf.setEnabled(band);
        btnCP.setEnabled(band);
        btnTI.setEnabled(band);
        btnImpCod.setEnabled(band);
        btnGuardar.setEnabled(band);
    }
    
    private void deshabilitarComponentesM2() {
        Utiles.deshabilitarCampo(edtCodigo);
        Utiles.deshabilitarCampo(edtCodigoLote);
    }

    private void habilitarComponentes() {
        boolean band = true;

        edtDescripcion.setEnabled(band);
        edtCantEnt.setEnabled(band);
        edtCostoUnitario.setEnabled(band);
        edtPrecioVenta.setEnabled(band);
        btnCP.setEnabled(band);
        btnTI.setEnabled(band);
        btnImpCod.setEnabled(band);
        btnGuardar.setEnabled(band);
    }

    //************************  Acciones ************************************************
    
     /**
     *
     * VALIDACIONES DE CAMPOS
     *
     */
    private boolean existenCamposBlancos() {
        boolean bandera = false;
        String codigo = this.edtCodigo.getText();
        String descripcion = this.edtDescripcion.getText();
        String cantEnt = this.edtCantEnt.getText();
        String precioCosto = this.edtCostoUnitario.getText();
        String precioVenta = this.edtPrecioVenta.getText();
        String undOfer = this.edtUnidOf.getText();

        if (codigo == null || codigo.isEmpty()) {
            bandera = true;
        }
        if (descripcion == null || descripcion.isEmpty()) {
            bandera = true;
        }
        if (cantEnt == null || cantEnt.isEmpty()) {
            bandera = true;
        }
        if (precioCosto == null || precioCosto.isEmpty()) {
            bandera = true;
        }
        if (precioVenta == null || precioVenta.isEmpty()) {
            bandera = true;
        }
        if (undOfer == null || undOfer.isEmpty()) {
            bandera = true;
        }

        return bandera;
    }

    private boolean existenCamposNoHomogeneos() {
        boolean bandera = false;

        try {
            int cantEnt = new Integer(this.edtCantEnt.getText());

            if (cantEnt < 0) {
                bandera = true;
            }
        } catch (Exception e) {
            bandera = true;
        }
        
        try {
            BigDecimal precioCosto = new BigDecimal(this.edtCostoUnitario.getText());
            BigDecimal precioVenta = new BigDecimal(this.edtPrecioVenta.getText());

            if (precioCosto.doubleValue() >= precioVenta.doubleValue()) {
                bandera = true;
            }
            
            if (precioCosto.doubleValue() < 0 || precioVenta.doubleValue() < 0)
            {
                bandera = true;
            }
        } catch (Exception e) {
            bandera = true;
        }

        return bandera;
    }

    private Clave iniciarProc1() {

        String codigo = Utiles.obtenerValor(edtCodigo);
        Clave result = Clave.RESULT_OK;

        try {
            if (gestor.consultarInvPorCodigo(codigo)) {
                inv = gestor.obtenerInvPorCodigoM2(codigo);
            }
        } catch (Exception e) {
            e.printStackTrace();
             return Clave.RESULT_ERROR_BD;
        }
        
        if (inv == null) {
            Utiles.establecerFocus2(edtCodigo);
            Mensaje.mostrarMensajeNoEncontrado(this);
            Utiles.requerirFocus(edtCodigo);
        } else {
            Utiles.establecerFocus1(edtCodigo);
            deshabilitarComponentesM2();
            habilitarComponentes();
            inicializarComponentes();
        }

        return result;
    }
    
    private Clave iniciarProc2()
    {
        Clave result = Clave.RESULT_OK;

        if (existenCamposBlancos() || existenCamposNoHomogeneos()) {
            return result = Clave.RESULT_ERROR_CAMPOS_INVALIDOS;
        }

        try {
            codigo = edtCodigo.getText().trim();
            codigoLote = edtCodigoLote.getText().trim();
            descripcion = edtDescripcion.getText().trim();
            cantEntrada = new Integer(edtCantEnt.getText().trim());
            costoUnit = new BigDecimal(edtCostoUnitario.getText().trim());
            precioVenta = new BigDecimal(edtPrecioVenta.getText().trim());
            unidOfert = new Integer(edtUnidOf.getText().trim());
            
        } catch (Exception e) {
            e.printStackTrace();
            return result = Clave.RESULT_ERROR_CAMPOS_INVALIDOS;
        }
        
        try {
            gestor.actulizarInventario(codigo, codigoLote, descripcion, cantEntrada,
                    costoUnit, precioVenta);
        } catch (Exception e) {
            e.printStackTrace();
            return Clave.RESULT_ERROR_BD;
        }
        
        try {
            gestor.guardarEntrada(inv, descripcion, cantEntrada, costoUnit, precioVenta);
        } catch (Exception e) {
            e.printStackTrace();
            return Clave.RESULT_ERROR_BD;
        }
        
        return result;
    }
}
