/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.libreria.gral.system.ui;

import com.mycompany.libreria.gral.system.controller.GestorLibreriaGralSystem;
import com.mycompany.libreria.gral.system.model.Inventario;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utiles.Clave;
import utiles.GenerarNumeros;
import utiles.Mensaje;
import utiles.Utiles;

/**
 *
 * @author Kevin
 */
public class FGenerarNumeros extends javax.swing.JFrame {

    private GestorLibreriaGralSystem gestor;
    private MainFrame mainFrame;
    private List<Inventario> lInv;

    /**
     * Creates new form FGenerarCodigo
     */
    public FGenerarNumeros(MainFrame mainFrame, GestorLibreriaGralSystem gestor) {
        initComponents();
        this.gestor = gestor;
        this.mainFrame = mainFrame;
        this.lInv = new ArrayList<>();
        limpiar();
        iniciarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgOpciones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        edtCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        edtCodigoLote = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtInventario = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        rbGrande = new javax.swing.JRadioButton();
        rbMediano = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        mbGenerarCodigo = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        mItemCerrarForm = new javax.swing.JMenuItem();
        menuLimpiar = new javax.swing.JMenu();
        mItemLimpiarLista = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Generar números");
        setAlwaysOnTop(true);
        setResizable(false);

        edtCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtCodigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtCodigoFocusLost(evt);
            }
        });
        edtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtCodigoKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Código :");

        edtCodigoLote.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtCodigoLote.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtCodigoLoteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtCodigoLoteFocusLost(evt);
            }
        });
        edtCodigoLote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCodigoLoteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtCodigoLoteKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Código de Lote :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edtCodigoLote, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(edtCodigoLote, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jtInventario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N°", "Código de Lote", "Código", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtInventario.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jtInventario.setRowHeight(30);
        jtInventario.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jtInventario.getTableHeader().setResizingAllowed(false);
        jtInventario.getTableHeader().setReorderingAllowed(false);
        jtInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtInventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtInventario);
        if (jtInventario.getColumnModel().getColumnCount() > 0) {
            jtInventario.getColumnModel().getColumn(0).setPreferredWidth(30);
            jtInventario.getColumnModel().getColumn(1).setPreferredWidth(140);
            jtInventario.getColumnModel().getColumn(2).setPreferredWidth(200);
            jtInventario.getColumnModel().getColumn(3).setPreferredWidth(500);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        bgOpciones.add(rbGrande);
        rbGrande.setText("Grande");

        bgOpciones.add(rbMediano);
        rbMediano.setText("Mediano");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Tamaño");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEliminar)
                .addGap(259, 259, 259)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbGrande)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbMediano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImprimir)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminar)
                        .addComponent(btnImprimir)
                        .addComponent(btnCancelar)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbGrande)
                        .addComponent(rbMediano)))
                .addContainerGap())
        );

        menuArchivo.setText("Archivo");

        mItemCerrarForm.setText("Cerrar");
        mItemCerrarForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemCerrarFormActionPerformed(evt);
            }
        });
        menuArchivo.add(mItemCerrarForm);

        mbGenerarCodigo.add(menuArchivo);

        menuLimpiar.setText("Lista");

        mItemLimpiarLista.setText("Limpiar lista de impresión");
        mItemLimpiarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemLimpiarListaActionPerformed(evt);
            }
        });
        menuLimpiar.add(mItemLimpiarLista);

        mbGenerarCodigo.add(menuLimpiar);

        setJMenuBar(mbGenerarCodigo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCodigoFocusGained
        // TODO add your handling code here:
        Utiles.establecerFocusActivoG(edtCodigo);
    }//GEN-LAST:event_edtCodigoFocusGained

    private void edtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCodigoFocusLost
        // TODO add your handling code here:
        Utiles.establecerFocusInactivo(edtCodigo);
    }//GEN-LAST:event_edtCodigoFocusLost

    private void edtCodigoLoteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCodigoLoteFocusGained
        // TODO add your handling code here:
        Utiles.establecerFocusActivoG(edtCodigoLote);
    }//GEN-LAST:event_edtCodigoLoteFocusGained

    private void edtCodigoLoteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCodigoLoteFocusLost
        // TODO add your handling code here:
        Utiles.establecerFocusInactivo(edtCodigoLote);
    }//GEN-LAST:event_edtCodigoLoteFocusLost

    private void edtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        
        if (key == KeyEvent.VK_ENTER) {
            Clave result = Clave.RESULT_OK;

            try {
                iniciarProc2();
            } catch (Exception e) {
                e.printStackTrace();
                result = Clave.RESULT_ERROR;
            }

            switch (result) {
                case RESULT_ERROR_BD: {
                    Mensaje.mostrarMensaje3(rootPane);
                    break;
                }
                case RESULT_ERROR: {
                    Mensaje.mostrarMensaje5(rootPane);
                    break;
                }
            }
        }
    }//GEN-LAST:event_edtCodigoKeyPressed

    private void edtCodigoLoteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoLoteKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        
        if (key == KeyEvent.VK_ENTER) {
            Clave result = Clave.RESULT_OK;
            
            try {
                iniciarProc4();
            } catch (Exception e) {
                e.printStackTrace();
                result = Clave.RESULT_ERROR;
            }

            switch (result) {
                case RESULT_ERROR_BD: {
                    Mensaje.mostrarMensaje3(rootPane);
                    break;
                }
                case RESULT_ERROR: {
                    Mensaje.mostrarMensaje5(rootPane);
                    break;
                }
            }
        }
    }//GEN-LAST:event_edtCodigoLoteKeyPressed

    private void jtInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtInventarioMouseClicked
        // TODO add your handling code here:
        this.edtCodigo.requestFocus();
        this.edtCodigo.selectAll();
    }//GEN-LAST:event_jtInventarioMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int index = this.jtInventario.getSelectedRow();
        int N = this.lInv.size();

        try {
            if (index < 0 || index > N) {
                Mensaje.mostrarMensajeSeleccion(rootPane);
            } else {
                lInv.remove(index);
                limpiarTabla();
                cargarListaEnTabla(lInv);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        Utiles.seleccionarFila0(jtInventario);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:

        if (lInv.isEmpty()) {
            Mensaje.mostrarMensaje16(rootPane);
        } else {
            if (!rbGrande.isSelected() && !rbMediano.isSelected()) {
                Mensaje.mostrarMensajeSeleccionTam(this);
            } else {
                int RESULT_OPTION = JOptionPane.CANCEL_OPTION;

                RESULT_OPTION = JOptionPane.showConfirmDialog(this,
                        "Desea imprimir la lista?",
                        "Confirmar salida", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (RESULT_OPTION == JOptionPane.OK_OPTION) {
                    GenerarNumeros reporte = new GenerarNumeros(lInv);

                    int opcion = -1;

                    if (rbGrande.isSelected()) {
                        opcion = 1;
                    }

                    if (rbMediano.isSelected()) {
                        opcion = 2;
                    }

                    try {
                        reporte.toViewReport(opcion);
                    } catch (Exception e) {
                        e.printStackTrace();
                        Mensaje.mostrarMensajeErrorGenerarReporte(rootPane);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void edtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoKeyTyped
        // TODO add your handling code here:
        int comilla = 39;

        if (evt.getKeyChar() == comilla)
        {
            evt.consume();
            return;
        }
    }//GEN-LAST:event_edtCodigoKeyTyped

    private void edtCodigoLoteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoLoteKeyTyped
        // TODO add your handling code here:
        int comilla = 39;

        if (evt.getKeyChar() == comilla)
        {
            evt.consume();
            return;
        }
    }//GEN-LAST:event_edtCodigoLoteKeyTyped

    private void mItemCerrarFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemCerrarFormActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mItemCerrarFormActionPerformed

    private void mItemLimpiarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemLimpiarListaActionPerformed
        // TODO add your handling code here:
        resetear();
        actualizar();
    }//GEN-LAST:event_mItemLimpiarListaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgOpciones;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JTextField edtCodigoLote;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtInventario;
    private javax.swing.JMenuItem mItemCerrarForm;
    private javax.swing.JMenuItem mItemLimpiarLista;
    private javax.swing.JMenuBar mbGenerarCodigo;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuLimpiar;
    private javax.swing.JRadioButton rbGrande;
    private javax.swing.JRadioButton rbMediano;
    // End of variables declaration//GEN-END:variables

    //************************************ Formulario ***********************************
    private void iniciarFormulario() {
        iniciarConfiguracion();
        
        try {
            iniciarProc1();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        cargarInformacion();
    }
    
    private void limpiar() {
        limpiarCampos();
        limpiarTabla();
    }

    private void limpiarCampos() {
        final String CAMPO_BLANCO = "";
        this.edtCodigo.setText(CAMPO_BLANCO);
        this.edtCodigoLote.setText(CAMPO_BLANCO);
    }

    private void limpiarTabla() {
        Utiles.limpiarTabla(jtInventario);
    }
    
   private void cargarListaEnTabla(List<Inventario> l) {  
        if (l == null || l.isEmpty()) {
            // Hacer nada.
        } else {
            int INDEX = -1;
            int NRO = 0;
            DefaultTableModel model = (DefaultTableModel) this.jtInventario.getModel();

            for (Inventario e : l) {
                INDEX++;
                NRO++;
                String[] datos = {
                    String.valueOf(NRO),
                    e.getProducto().getCodigoLote(),
                    e.getProducto().getCodigo(),
                    e.getProducto().getDescripcion(),};
                
                model.insertRow(INDEX, datos);
            }
        }
    }
    
    private void iniciarConfiguracion()
    {
        Utiles.establecerFocusActivoG(edtCodigo);
    }
    
    private void cargarInformacion()
    {
        limpiarTabla();
        cargarListaEnTabla(lInv);
    }

    private void actualizar()
    {
        limpiarTabla();
        cargarListaEnTabla(lInv);
        Utiles.seleccionarFila0(jtInventario);
        Utiles.posicionarPrincipio(jtInventario);
    }
    
    private void resetear()
    {
        lInv.clear();
    }
    //******************************* Procedimientos ***********************************
    
    private void iniciarProc1() {
        List<Inventario> lRetorno = new ArrayList<>();

        lRetorno = gestor.obtenerInvPorCodigoM1(mainFrame.obtenerListaImpresion());

        lInv.addAll(lRetorno);
    }
    
    private void iniciarProc2() {
        String codigo = this.edtCodigo.getText().trim();
        
        if (codigo == null || codigo.isEmpty()) {
            // Hacer nada.
        } else {
            Clave result = iniciarProc3(codigo);

            switch(result)
            {
                case RESULT_EXISTE: {
                    Utiles.limpiarSeleccion(jtInventario);
                    final int COL_CODIGO = 2;

                    Utiles.seleccionarFila(jtInventario, COL_CODIGO, codigo);
                    break;
                }
                case RESULT_NO_EXISTE: {
                    Mensaje.mostrarMensajeNoEncontrado(rootPane);
                    break;
                }
                case RESULT_OK:
                {
                    limpiarTabla();
                    cargarListaEnTabla(lInv);
                    Utiles.seleccionarFila0(jtInventario);
                    break;
                }
            }
        }
        
        Utiles.establecerFocusActivoG(edtCodigo);
    }
    
    private Clave iniciarProc3(String codigo) {
        Clave result = Clave.RESULT_OK;
        Inventario inv = null;

        if (gestor.consultarInvPorCodigo(codigo)) {
            inv = gestor.obtenerInventariosPorCodigo(codigo).get(0);
        } else {
            result = Clave.RESULT_NO_EXISTE;
        }

        if (inv == null) {
            // Hacer nada.
        } else {
            agregarALista(inv);
        }
        return result;
    }
    
    private void iniciarProc4() throws Exception{
        String codLote = edtCodigoLote.getText().trim();

        if (codLote == null || codLote.isEmpty()) {
            // Hacer nada.
        } else {
            iniciarProc5(codLote);
            limpiarTabla();
            cargarListaEnTabla(lInv);
            iniciarProc6(codLote);
        }
        
        Utiles.establecerFocusActivoG(edtCodigo);
    }
    
    private void iniciarProc5(String codLote) {

        if (gestor.consultarInventarioPorCodigoLote(codLote)) {
            List<Inventario> list = gestor.obtenerInventariosPorCodigoLote(codLote);
            
            agregarALista(list);
        } else {
            Mensaje.mostrarMensajeNoEncontrado(rootPane);
        }
    }
    
    private void iniciarProc6(String codLote) {
        if (codLote == null || codLote.isEmpty()) {
            // Hacer nada.
        } else {
            Utiles.limpiarSeleccion(jtInventario);
            final int COL_CODIGO_LOTE = 1;

            Utiles.seleccionarFila(jtInventario, COL_CODIGO_LOTE, codLote);
        }
    }
    
    private void agregarALista(Inventario inv) {
        lInv.add(inv);
    }
    
    private void agregarALista(List<Inventario> lista)
    {
        for (Inventario inv : lista) {

            agregarALista(inv);
        }
    }
}
