/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.libreria.gral.system.ui;

import com.mycompany.libreria.gral.system.controller.GestorLibreriaGralSystem;
import com.mycompany.libreria.gral.system.model.Codigo;
import com.mycompany.libreria.gral.system.model.Inventario;
import com.mycompany.libreria.gral.system.model.Oferta;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import utiles.Clave;
import utiles.Mensaje;
import utiles.Utiles;
import static utiles.Utiles.establecerFocus1;

/**
 *
 * @author KEVIN
 */
public class FModificarInventario extends javax.swing.JFrame {

    private GestorLibreriaGralSystem gestor;
    private MainFrame mainFrame;
    private FModificarInventarioPorLote form;
    private boolean bandCerrar;

    private StringBuffer codigoBusqCamp;
    private StringBuffer codigoBusqSP;
    private StringBuffer codigoBusqOtro;
    private String codigo;
    private String codigoLote;
    private String descripcion;
    private int stock;
    private BigDecimal costoUnit;
    private BigDecimal precioVenta;
    private int unidOfert;
    private int acumEnt;
    private int acumSal;
    private List<Oferta> lOfertas;
    private boolean estado;
    private Inventario inv;
    private List<Codigo> lCodigo;
    private boolean estadoSeguro;

    /**
     * Creates new form FrameAlta
     */
    public FModificarInventario(MainFrame mainFrame, GestorLibreriaGralSystem gestor) {
        initComponents();
        this.mainFrame = mainFrame;
        this.form = null;
        this.gestor = gestor;
        this.bandCerrar = false;

        this.reiniciarValoresLogicos();
        this.limpiarFormulario();
        this.iniciarFormulario();
    }

    public FModificarInventario(MainFrame mainFrame,
            GestorLibreriaGralSystem gestor, String value) {
        initComponents();
        this.mainFrame = mainFrame;
        this.form = null;
        this.gestor = gestor;
        this.bandCerrar = true;

        this.reiniciarValoresLogicos();
        this.limpiarFormulario();
        this.cargarValoresExtra(value);
        this.iniciarFormulario();
    }

    public FModificarInventario(MainFrame mainFrame, GestorLibreriaGralSystem gestor, String codigo, boolean band, Clave codAccion) {
        initComponents();
        this.mainFrame = mainFrame;
        this.form = null;
        this.gestor = gestor;
        this.bandCerrar = band;

        this.reiniciarValoresLogicos();
        this.limpiarFormulario();
        this.cargarValoresExtra(codigo);
        this.iniciarFormulario();
    }

    public FModificarInventario(FModificarInventarioPorLote form, MainFrame mainFrame, GestorLibreriaGralSystem gestor, String codigo, boolean band) {
        initComponents();
        this.mainFrame = mainFrame;
        this.form = form;
        this.gestor = gestor;
        this.bandCerrar = band;

        this.reiniciarValoresLogicos();
        this.limpiarFormulario();
        this.cargarValoresExtra(codigo);
        this.iniciarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        edtDescripcion = new javax.swing.JTextField();
        edtCodigo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        edtCodigoLote = new javax.swing.JTextField();
        btnMasCod = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        edtCostoUnitario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        edtStock = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        edtUnidOf = new javax.swing.JTextField();
        edtPrecioVenta = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnLOfertas = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnImpCod = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnTI = new javax.swing.JButton();
        btnCP = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        edtAcumEntrada = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        edtAcumSalida = new javax.swing.JTextField();
        cbEstSeguro = new javax.swing.JCheckBox();
        menuBarra = new javax.swing.JMenuBar();
        mCerrar = new javax.swing.JMenu();
        mItemCerrar = new javax.swing.JMenuItem();
        mEditar = new javax.swing.JMenu();
        mItemCodBusq = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar inventario");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Código de Lote :");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        edtDescripcion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtDescripcionKeyTyped(evt);
            }
        });

        edtCodigo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        edtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtCodigoFocusGained(evt);
            }
        });
        edtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtCodigoKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Código :");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Descripción :");

        edtCodigoLote.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtCodigoLote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtCodigoLoteKeyTyped(evt);
            }
        });

        btnMasCod.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMasCod.setText("+");
        btnMasCod.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMasCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasCodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnMasCod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtCodigoLote, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(edtCodigoLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMasCod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        edtCostoUnitario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtCostoUnitario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        edtCostoUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtCostoUnitarioKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Stock:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Costo unit. :");

        edtStock.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtStock.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        edtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtStockKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edtCostoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtCostoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        edtUnidOf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtUnidOf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        edtUnidOf.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        edtUnidOf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtUnidOfKeyTyped(evt);
            }
        });

        edtPrecioVenta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtPrecioVenta.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        edtPrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtPrecioVentaKeyTyped(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Unid. ofertadas :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Precio unit. :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("*");

        btnLOfertas.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnLOfertas.setText("+");
        btnLOfertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLOfertasActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("*");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edtUnidOf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(33, 33, 33)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(edtPrecioVenta)
                        .addComponent(btnLOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(edtUnidOf)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnImpCod.setText("Imp. cod.");
        btnImpCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpCodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImpCod)
                .addGap(193, 193, 193)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImpCod))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnTI.setText("Tomar una instantánea");

        btnCP.setText("Cargar desde el PC");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Imagen :");

        jLabel1.setText("...ruta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCP, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnTI, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCP)
                    .addComponent(btnTI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Estado: ");

        cbEstado.setEditable(true);
        cbEstado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Activo" }));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("Tot. de Entradas :");

        edtAcumEntrada.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtAcumEntrada.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        edtAcumEntrada.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        edtAcumEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtAcumEntradaKeyTyped(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("Tot. de Salidas:");

        edtAcumSalida.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edtAcumSalida.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        edtAcumSalida.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        edtAcumSalida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtAcumSalidaKeyTyped(evt);
            }
        });

        cbEstSeguro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbEstSeguro.setText("E.S.");
        cbEstSeguro.setIconTextGap(8);
        cbEstSeguro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbEstSeguroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edtAcumEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edtAcumSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbEstSeguro)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbEstSeguro))
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtAcumSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtAcumEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mCerrar.setText("Archivo");

        mItemCerrar.setText("Cerrar");
        mItemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemCerrarActionPerformed(evt);
            }
        });
        mCerrar.add(mItemCerrar);

        menuBarra.add(mCerrar);

        mEditar.setText("Editar");

        mItemCodBusq.setText("Código de Busqueda");
        mItemCodBusq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemCodBusqActionPerformed(evt);
            }
        });
        mEditar.add(mItemCodBusq);

        menuBarra.add(mEditar);

        setJMenuBar(menuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtStockKeyTyped
        // TODO add your handling code here:

        char car = evt.getKeyChar();

        if (car >= '0' & car <= '9') {
            // Hacer nada.
        } else {
            evt.consume();
        }

        Utiles.suprimirComilla(edtStock);
    }//GEN-LAST:event_edtStockKeyTyped

    private void edtCostoUnitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCostoUnitarioKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        if (car >= '0' && car <= '9') {
            // Hacer nada.
        } else {
            if (car == '.') {
                try {
                    String value = edtCostoUnitario.getText();

                    if (value.contains(".")) {
                        evt.consume();
                    }
                } catch (Exception e) {
                    edtCostoUnitario.setText("");
                    evt.consume();
                }
            } else {
                evt.consume();
            }
        }

        Utiles.suprimirComilla(edtCostoUnitario);
    }//GEN-LAST:event_edtCostoUnitarioKeyTyped

    private void edtPrecioVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtPrecioVentaKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        if (car >= '0' && car <= '9') {
            // Hacer nada.
        } else {
            if (car == '.') {
                try {
                    String value = edtPrecioVenta.getText();

                    if (value.contains(".")) {
                        evt.consume();
                    }
                } catch (Exception e) {
                    edtPrecioVenta.setText("");
                    evt.consume();
                }
            } else {
                evt.consume();
            }
        }

        Utiles.suprimirComilla(edtPrecioVenta);
    }//GEN-LAST:event_edtPrecioVentaKeyTyped

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
        reiniciarValoresLogicos();
        iniciarFormulario();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        Clave result = Clave.RESULT_SIN_DEFINIR;

        try {
            result = iniciarProc3();
        } catch (Exception e) {
            result = Clave.RESULT_ERROR;
        }

        switch (result) {
            case RESULT_ERROR: {
                Mensaje.mostrarMensaje5(rootPane);
                dispose();
                break;
            }
            case RESULT_ERROR_CAMPOS_INVALIDOS: {
                Mensaje.mostrarMensaje2(this);
                break;
            }
            case RESULT_ERROR_BD: {
                Mensaje.mostrarMensaje3(this);
                dispose();
                break;
            }
            case RESULT_OK: {

                JOptionPane.showMessageDialog(rootPane, "Inventario guardado exitosamente!!");

                try {
                    mainFrame.actualizar();
                } catch (Exception e) {
                }

                if (form == null) {
                    // Hacer nada.
                } else {
                    form.iniciarProc11(Utiles.obtenerValor(edtCodigo));
                }

                if (bandCerrar) {
                    this.dispose();
                } else {
                    this.limpiarFormulario();
                    this.iniciarFormulario();
                }

                break;
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
        this.edtCodigo.transferFocus();
    }//GEN-LAST:event_formWindowDeactivated

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void edtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoKeyTyped
        // TODO add your handling code here:

        // Validaciones
        int comilla = 39;

        if (evt.getKeyChar() == comilla) {
            evt.consume();
        }

        Utiles.suprimirComilla(edtCodigo);
    }//GEN-LAST:event_edtCodigoKeyTyped

    private void btnImpCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpCodActionPerformed
        // TODO add your handling code here:
        if (mainFrame != null) {
            String cod = null;

            try {
                cod = edtCodigo.getText().trim();
            } catch (Exception e) {
            }

            if (cod == null || cod.isEmpty()) {
                Mensaje.mostrarMensajeImp(this);
                return;
            }

            mainFrame.iniciarProc23(cod);
            JOptionPane.showMessageDialog(this, "Agregado a la lista de impresión!");
        }
    }//GEN-LAST:event_btnImpCodActionPerformed

    private void edtUnidOfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtUnidOfKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        if (car >= '0' & car <= '9') {
            // Hacer nada.
        } else {
            evt.consume();
        }

        Utiles.suprimirComilla(edtUnidOf);
    }//GEN-LAST:event_edtUnidOfKeyTyped

    private void btnLOfertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLOfertasActionPerformed
        // TODO add your handling code here:

        FOfertasMI formOfertas = new FOfertasMI(gestor, codigo, lOfertas);

        formOfertas.setVisible(true);
    }//GEN-LAST:event_btnLOfertasActionPerformed

    private void edtAcumEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtAcumEntradaKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        if (car >= '0' & car <= '9') {
            // Hacer nada.
        } else {
            evt.consume();
        }

        Utiles.suprimirComilla(edtAcumEntrada);
    }//GEN-LAST:event_edtAcumEntradaKeyTyped

    private void edtAcumSalidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtAcumSalidaKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        if (car >= '0' & car <= '9') {
            // Hacer nada.
        } else {
            evt.consume();
        }

        Utiles.suprimirComilla(edtAcumSalida);
    }//GEN-LAST:event_edtAcumSalidaKeyTyped

    private void edtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Clave result = Clave.RESULT_SIN_DEFINIR;

            try {
                result = iniciarProc1();
            } catch (Exception e) {
                e.printStackTrace();
                result = Clave.RESULT_ERROR;
            }

            switch (result) {
                case RESULT_ERROR_BD: {
                    Mensaje.mostrarMensaje3(rootPane);
                    break;
                }
                case RESULT_ERROR: {
                    Mensaje.mostrarMensaje5(rootPane);
                    break;
                }
            }
        }
    }//GEN-LAST:event_edtCodigoKeyPressed

    private void edtCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCodigoFocusGained
        // TODO add your handling code here:
        Utiles.requerirFocus(edtCodigo);
    }//GEN-LAST:event_edtCodigoFocusGained

    private void mItemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mItemCerrarActionPerformed

    private void mItemCodBusqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemCodBusqActionPerformed
        // TODO add your handling code here:
        FCodigoBusqueda form = new FCodigoBusqueda(codigoBusqCamp,
                codigoBusqSP,
                codigoBusqOtro,
                true);

        form.setVisible(true);
        this.cbEstSeguro.setSelected(false);
    }//GEN-LAST:event_mItemCodBusqActionPerformed

    private void edtCodigoLoteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoLoteKeyTyped
        // TODO add your handling code here:
        Utiles.suprimirComilla(evt);
        Utiles.suprimirComilla(edtCodigoLote);
    }//GEN-LAST:event_edtCodigoLoteKeyTyped

    private void edtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtDescripcionKeyTyped
        // TODO add your handling code here:
        Utiles.suprimirComilla(evt);
        Utiles.suprimirComilla(edtDescripcion);
    }//GEN-LAST:event_edtDescripcionKeyTyped

    private void btnMasCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasCodActionPerformed
        // TODO add your handling code here:
        FCodigo form = new FCodigo(gestor, lCodigo, codigo, Clave.MENSAJE_MODIFICAR_INVENTARIO, this);

        form.setVisible(true);
    }//GEN-LAST:event_btnMasCodActionPerformed

    private void cbEstSeguroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbEstSeguroMouseClicked
        // TODO add your handling code here
        if (codigoBusqCamp.toString().trim().isEmpty()
                & codigoBusqSP.toString().trim().isEmpty()
                & codigoBusqOtro.toString().trim().isEmpty()) {
            this.cbEstSeguro.setSelected(false);
        }
    }//GEN-LAST:event_cbEstSeguroMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCP;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImpCod;
    private javax.swing.JButton btnLOfertas;
    private javax.swing.JButton btnMasCod;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnTI;
    private javax.swing.JCheckBox cbEstSeguro;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JTextField edtAcumEntrada;
    private javax.swing.JTextField edtAcumSalida;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JTextField edtCodigoLote;
    private javax.swing.JTextField edtCostoUnitario;
    private javax.swing.JTextField edtDescripcion;
    private javax.swing.JTextField edtPrecioVenta;
    private javax.swing.JTextField edtStock;
    private javax.swing.JTextField edtUnidOf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JMenu mCerrar;
    private javax.swing.JMenu mEditar;
    private javax.swing.JMenuItem mItemCerrar;
    private javax.swing.JMenuItem mItemCodBusq;
    private javax.swing.JMenuBar menuBarra;
    // End of variables declaration//GEN-END:variables

    //***************************** Formulario *******************************************
    /**
     * Limpieza de componentes
     */
    private void limpiarFormulario() {
        limpiarCamposDeTexto();
        Utiles.limpiarCampo(edtCodigo);
        Utiles.descolorear(btnMasCod);
        this.cbEstSeguro.setSelected(false);
    }

    private void limpiarCamposDeTexto() {
        this.edtCodigo.setText("");
        this.edtCodigoLote.setText("");
        this.edtDescripcion.setText("");
        this.edtStock.setText("");
        this.edtCostoUnitario.setText("");
        this.edtPrecioVenta.setText("");
        this.edtUnidOf.setText("");
        this.edtAcumEntrada.setText("");
        this.edtAcumSalida.setText("");
    }

    private void reiniciarValoresLogicos() {

        codigoBusqCamp = new StringBuffer();
        codigoBusqSP = new StringBuffer();
        codigoBusqOtro = new StringBuffer();
        codigo = "";
        codigoLote = "";
        descripcion = "";
        stock = 0;
        costoUnit = new BigDecimal(0);
        precioVenta = new BigDecimal(0);
        unidOfert = 0;
        acumEnt = 0;
        acumSal = 0;
        lOfertas = new ArrayList<>();
        estado = false;
        inv = null;
        acumEnt = 0;
        acumSal = 0;
        estadoSeguro = false;
    }

    private void inicializarComponentes() {

        codigoBusqCamp.append(inv.getProducto().getCodigoBusq1());
        codigoBusqSP.append(inv.getProducto().getCodigoBusq2());
        codigoBusqOtro.append(inv.getProducto().getCodigoBusq3());
        codigo = inv.getProducto().getCodigo();
        codigoLote = inv.getProducto().getCodigoLote();
        descripcion = inv.getProducto().getDescripcion();
        stock = inv.getProducto().getStock();
        costoUnit = inv.getCostoUnitario();
        unidOfert = inv.getUnidOf();
        precioVenta = inv.getpVenta();
        lOfertas = new ArrayList<>(inv.getlOferta());
        estado = inv.isEstado();
        acumEnt = inv.getAcumEntrada();
        acumSal = inv.getAcumSalida();
        lCodigo = inv.getProducto().getListaCodigo();
        estadoSeguro = inv.getProducto().isEstadoSeguro();

        // Campos
        edtCodigo.setText(codigo);
        edtCodigoLote.setText(codigoLote);
        edtDescripcion.setText(descripcion);
        edtStock.setText(String.valueOf(stock));
        edtCostoUnitario.setText(String.valueOf(costoUnit));
        edtUnidOf.setText(String.valueOf(unidOfert));
        edtPrecioVenta.setText(String.valueOf(precioVenta));
        edtAcumEntrada.setText(String.valueOf(acumEnt));
        edtAcumSalida.setText(String.valueOf(acumSal));

        if (estado) {
            cbEstado.setSelectedIndex(1);
        } else {
            cbEstado.setSelectedIndex(0);
        }

        cbEstSeguro.setSelected(estadoSeguro);
    }

    private void iniciarFormulario() {
        edtCodigo.setEnabled(true);
        deshabilitarComponentes();
        cbEstado.setSelectedIndex(0);
        btnLOfertas.setBackground(new Color(240, 240, 240));
    }

    private void deshabilitarComponentes() {
        boolean band = false;

        edtCodigoLote.setEnabled(band);
        edtDescripcion.setEnabled(band);
        edtStock.setEnabled(band);
        edtCostoUnitario.setEnabled(band);
        edtPrecioVenta.setEnabled(band);
        edtUnidOf.setEnabled(band);
        btnCP.setEnabled(band);
        btnTI.setEnabled(band);
        btnImpCod.setEnabled(band);
        btnGuardar.setEnabled(band);
        btnLOfertas.setEnabled(band);
        cbEstado.setEnabled(band);
        edtAcumEntrada.setEnabled(band);
        edtAcumSalida.setEnabled(band);
        mItemCodBusq.setEnabled(band);
        cbEstSeguro.setEnabled(band);
    }

    private void habilitarComponentes() {
        boolean band = true;

        edtCodigoLote.setEnabled(band);
        edtDescripcion.setEnabled(band);
        edtStock.setEnabled(band);
        edtCostoUnitario.setEnabled(band);
        edtPrecioVenta.setEnabled(band);
        btnCP.setEnabled(band);
        btnTI.setEnabled(band);
        btnImpCod.setEnabled(band);
        edtUnidOf.setEnabled(band);
        edtAcumEntrada.setEnabled(band);
        edtAcumSalida.setEnabled(band);
        btnLOfertas.setEnabled(band);
        btnGuardar.setEnabled(band);
        /// cbEstado.setEnabled(band);
        mItemCodBusq.setEnabled(band);
        cbEstSeguro.setEnabled(band);
    }

    public StringBuffer getCodigoBusqueda() {
        return codigoBusqCamp;
    }

    public void setCodigoBusqueda(String value) {
        this.codigoBusqCamp.delete(0, codigoBusqCamp.length());
        this.codigoBusqCamp.append(value);
    }

    public void actualizar() {
        if (lCodigo.isEmpty()) {
            Utiles.descolorear(btnMasCod);
        } else {
            Utiles.descolorear(btnMasCod);
            for (Codigo codigo : lCodigo) {
                if (codigo.isEstado()) {
                    Utiles.colorearRojo(btnMasCod);
                    break;
                }
            }
        }
    }

    //************************  Acciones ************************************************
    /**
     *
     * VALIDACIONES DE CAMPOS
     *
     */
    private boolean existenCamposBlancos() {
        boolean bandera = false;
        String codigo = this.edtCodigo.getText();
        String descripcion = this.edtDescripcion.getText();
        String cantEnt = this.edtStock.getText();
        String precioCosto = this.edtCostoUnitario.getText();
        String precioVenta = this.edtPrecioVenta.getText();
        String undOfer = this.edtUnidOf.getText();
        String acumEnt = edtAcumEntrada.getText();
        String acumSal = edtAcumSalida.getText();

        if (codigo == null || codigo.isEmpty()) {
            bandera = true;
        }
        if (descripcion == null || descripcion.isEmpty()) {
            bandera = true;
        }
        if (cantEnt == null || cantEnt.isEmpty()) {
            bandera = true;
        }
        if (precioCosto == null || precioCosto.isEmpty()) {
            bandera = true;
        }
        if (precioVenta == null || precioVenta.isEmpty()) {
            bandera = true;
        }
        if (undOfer == null || undOfer.isEmpty()) {
            bandera = true;
        }

        if (acumEnt == null || acumEnt.isEmpty()) {
            bandera = true;
        }

        if (acumSal == null || acumSal.isEmpty()) {
            bandera = true;
        }

        return bandera;
    }

    private boolean existenCamposNoHomogeneos() {
        boolean bandera = false;

        try {
            int cantEnt = new Integer(this.edtStock.getText());

            if (cantEnt < 0) {
                bandera = true;
            }
        } catch (Exception e) {
            bandera = true;
        }

        try {
            int undOfert = new Integer(this.edtUnidOf.getText());

            if (undOfert < 1) {
                bandera = true;
            }
        } catch (Exception e) {
            bandera = true;
        }

        try {
            BigDecimal precioCosto = new BigDecimal(this.edtCostoUnitario.getText());
            BigDecimal precioVenta = new BigDecimal(this.edtPrecioVenta.getText());

            if (precioCosto.doubleValue() < 0 || precioVenta.doubleValue() < 0) {
                bandera = true;
            }

            if (precioCosto.doubleValue() >= precioVenta.doubleValue()) {
                JOptionPane.showMessageDialog(this, "El precio de costo es mayor o igual al precio de venta.");
                bandera = true;
            }
        } catch (Exception e) {
            bandera = true;
        }

        try {
            int numEnt = new Integer(this.edtAcumEntrada.getText());
            int numSal = new Integer(this.edtAcumSalida.getText());

            if (numEnt < 0 || numSal < 0) {
                bandera = true;
            }

            if (numSal > numEnt) {
                bandera = true;
            }
        } catch (Exception e) {
            bandera = true;
        }

        return bandera;
    }

    private void cargarValoresExtra(String value) {
        this.edtCodigo.setText(value);
    }

    /*
    * Procedimientos
     */
    private Clave iniciarProc1() {

        String codigo = Utiles.obtenerValor(edtCodigo);
        Clave result = Clave.RESULT_OK;

        try {
            if (gestor.consultarInvPorCodigo(codigo)) {
                inv = gestor.obtenerInvPorCodigoM2(codigo);
            }
        } catch (Exception e) {
            e.printStackTrace();
            return Clave.RESULT_ERROR_BD;
        }

        if (inv == null) {
            Utiles.establecerFocus2(edtCodigo);
            Mensaje.mostrarMensajeNoEncontrado(this);
        } else {
            establecerFocus1(edtCodigo);
            Utiles.deshabilitarCampo(edtCodigo);
            habilitarComponentes();
            inicializarComponentes();
            iniciarProc4();
            actualizar();
        }

        return result;
    }

    private Clave iniciarProc2() {
        Clave result = Clave.RESULT_OK;

        try {
            codigo = edtCodigo.getText().trim();
            codigoLote = edtCodigoLote.getText().trim();
            descripcion = edtDescripcion.getText().trim();
            stock = new Integer(edtStock.getText().trim());
            costoUnit = new BigDecimal(edtCostoUnitario.getText().trim());
            precioVenta = new BigDecimal(edtPrecioVenta.getText().trim());
            unidOfert = new Integer(edtUnidOf.getText().trim());
            acumEnt = new Integer(edtAcumEntrada.getText().trim());
            acumSal = new Integer(edtAcumSalida.getText().trim());

            if (codigoBusqCamp.toString().trim().isEmpty()
                    & codigoBusqSP.toString().trim().isEmpty()
                    & codigoBusqOtro.toString().trim().isEmpty()) {
                estadoSeguro = false;
            } else {
                if (cbEstSeguro.isSelected()) {
                    estadoSeguro = true;
                } else {
                    estadoSeguro = false;
                }
            }

            switch (cbEstado.getSelectedIndex()) {
                case 0:
                    estado = false;
                    break;
                case 1:
                    estado = true;
                    break;
            }
        } catch (Exception e) {
            e.printStackTrace();
            return result = Clave.RESULT_ERROR_CAMPOS_INVALIDOS;
        }

        try {
            gestor.guardarInv(codigoBusqCamp.toString(),
                    codigoBusqSP.toString(),
                    codigoBusqOtro.toString(),
                    codigo, codigoLote, descripcion, unidOfert, stock,
                    costoUnit, precioVenta, acumEnt, acumSal, lOfertas, estado, lCodigo, estadoSeguro);
        } catch (Exception e) {
            e.printStackTrace();
            return Clave.RESULT_ERROR_BD;
        }

        return result;
    }

    private Clave iniciarProc3() {
        Clave result = Clave.RESULT_SIN_DEFINIR;

        //  Validaciones
        if (existenCamposBlancos() || existenCamposNoHomogeneos()) {
            return Clave.RESULT_ERROR_CAMPOS_INVALIDOS;
        }

        try {
            result = iniciarProc2();
        } catch (Exception e) {
            e.printStackTrace();
            result = Clave.RESULT_ERROR;
        }

        return result;
    }

    private void iniciarProc4() {
        if (inv == null) {
            // Hacer nada.
        } else {
            if (inv.getlOferta().isEmpty()) {
                // Hacer nada.
            } else {
                btnLOfertas.setBackground(Color.red);
            }
        }
    }
}
