/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.libreria.gral.system.ui;

import com.mycompany.libreria.gral.system.model.Oferta;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.text.JTextComponent;
import utiles.Clave;
import utiles.Mensaje;
import utiles.Utiles;

/**
 *
 * @author KEVIN
 */
public class FOfertasAI extends javax.swing.JFrame {

    private final int COL_CODIGO = 0;
    private final int COL_DESC = 1;
    private final int COL_UNID_OFERTADAS = 2;
    private final int COL_PREC_VEN = 3;
    private String codigo;
    private List<Oferta> copLOfertas;
    private List<Oferta> origLOfertas;

    public FOfertasAI(String codigo, List<Oferta> l) {
        initComponents();

        this.codigo = codigo;
        origLOfertas = l;
        copLOfertas = new ArrayList<>(origLOfertas);
        limpiarFormulario();
        iniciarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopMTablaEntrada = new javax.swing.JPopupMenu();
        mItemCopiarCod = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOfertas = new javax.swing.JTable()
        {
            @Override
            public Component prepareEditor(TableCellEditor editor, int row, int column) {
                Component c = super.prepareEditor(editor, row, column);
                if (c instanceof JTextComponent) {
                    ((JTextComponent) c).selectAll();
                } 
                return c;
            }
        };
        jPanel1 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        mItemCopiarCod.setText("Copiar código");
        mItemCopiarCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemCopiarCodActionPerformed(evt);
            }
        });
        PopMTablaEntrada.add(mItemCopiarCod);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Ofertas <AI>");
        setAlwaysOnTop(true);
        setResizable(false);

        tablaOfertas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tablaOfertas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Unid. ofert.", "Precio unit."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaOfertas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaOfertas.setDragEnabled(true);
        tablaOfertas.setFocusCycleRoot(true);
        tablaOfertas.setRequestFocusEnabled(false);
        tablaOfertas.setRowHeight(32);
        tablaOfertas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaOfertas.getTableHeader().setReorderingAllowed(false);
        tablaOfertas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaOfertasKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaOfertasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tablaOfertasKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tablaOfertas);
        if (tablaOfertas.getColumnModel().getColumnCount() > 0) {
            tablaOfertas.getColumnModel().getColumn(0).setMinWidth(180);
            tablaOfertas.getColumnModel().getColumn(0).setPreferredWidth(180);
            tablaOfertas.getColumnModel().getColumn(1).setPreferredWidth(500);
            tablaOfertas.getColumnModel().getColumn(3).setPreferredWidth(160);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        try {
            origLOfertas.clear();
            origLOfertas.addAll(copLOfertas);
        } catch (Exception e) {
            e.printStackTrace();
            Mensaje.mostrarMensaje5(rootPane);
        }

        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void mItemCopiarCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemCopiarCodActionPerformed
        // TODO add your handling code here:
        Utiles.copiarAPortapapeles(tablaOfertas, COL_CODIGO);
    }//GEN-LAST:event_mItemCopiarCodActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        final int rowSel = tablaOfertas.getSelectedRow();

        //  Validaciones
        if (rowSel < 0) {
            Mensaje.mostrarMensajeSeleccion(this);
        } else {
            String codigo = (String) tablaOfertas.getValueAt(rowSel, COL_CODIGO);

            if (codigo == null || codigo.isEmpty()) {
                // Hacer nada.
                Mensaje.mostrarMensajeSeleccion(rootPane);
            } else {
                Clave result = Clave.RESULT_OK;
                // Acciones
                try {
                    result = eliminar(copLOfertas, codigo);
                } catch (Exception e) {
                    e.printStackTrace();
                    result = Clave.RESULT_ERROR;
                }

                switch (result) {
                    case RESULT_ERROR: {
                        Mensaje.mostrarMensaje5(rootPane);
                        break;
                    }
                    case RESULT_NO_EXISTE: {
                        Mensaje.mostrarMensajeSeleccion(rootPane);
                        break;
                    }
                    case RESULT_OK: {
                        // Hacer nada.
                        break;
                    }
                }
                
                this.actualizarForm();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        try {
            Oferta of = crearNuevaOferta();

            agregarALista(copLOfertas, of);
        } catch (Exception e) {
            e.printStackTrace();
            Mensaje.mostrarMensaje5(rootPane);
        }

        actualizarForm();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tablaOfertasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaOfertasKeyTyped
        // TODO add your handling code here:
        Utiles.suprimirComilla(evt);
    }//GEN-LAST:event_tablaOfertasKeyTyped

    private void tablaOfertasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaOfertasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaOfertasKeyPressed

    private void tablaOfertasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaOfertasKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_TAB)
        {
            Utiles.modoTabM1(tablaOfertas);
        }
    }//GEN-LAST:event_tablaOfertasKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu PopMTablaEntrada;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mItemCopiarCod;
    private javax.swing.JTable tablaOfertas;
    // End of variables declaration//GEN-END:variables

    //********************** Procedimientos ************************
    private void modificar(Oferta of, int columna, String value) {
       
        switch (columna) {
            case COL_DESC: {
                
                value = Utiles.limpiar(value, "'");
                
                if (value == null || value.isEmpty())
                {
                    // Hacer nada.
                } else
                {
                    of.setDescripcion(value);
                }                
                break;
            }
            case COL_UNID_OFERTADAS: {
                int unidOf;

                try {
                    unidOf = new Integer(value);
                } catch (Exception e) {
                    unidOf = 1;
                }

                if (unidOf < 1) {
                    unidOf = 1;
                }

                of.setUnidOfert(unidOf);
                break;
            }
            case COL_PREC_VEN: {
                BigDecimal precVenta;

                try {
                    precVenta = new BigDecimal(value);
                } catch (Exception e) {
                    precVenta = new BigDecimal(0);
                }

                if (precVenta.doubleValue() < 0) {
                    precVenta = new BigDecimal(0);
                }
                of.setPrecioVenta(precVenta);
                break;
            }
        }
    }

    private Oferta crearNuevaOferta() {
        String value = Oferta.generarCodigo(this.codigo);
        String desc = "nueva oferta.";
        int MIN_UNID_OF = 1;
        boolean EST_ACTIVO = true;
        BigDecimal pVenta = new BigDecimal(0);
        Oferta of = new Oferta();

        of.setDescripcion(desc);
        of.setCodigo(value);
        of.setUnidOfert(MIN_UNID_OF);
        of.setPrecioVenta(pVenta);
        of.setEstado(EST_ACTIVO);

        return of;
    }

    private void iniciarProc2() {

        final String value = Utiles.obtenerCambios(tablaOfertas);
        final String cod = Utiles.obtenerValor(tablaOfertas, COL_CODIGO);

        if (cod == null || cod.isEmpty()) {
        } else {
            if (consultar(copLOfertas, cod)) {

                Oferta of = obtener(copLOfertas, cod);

                modificar(of, tablaOfertas.getSelectedColumn(), value);
                
            }
        }
        actualizarForm();
        Utiles.seleccionarFila(tablaOfertas, tablaOfertas.getSelectedRow());
    }
    
    /**
     * Agrega una oferta a la nueva lista de ofertas.
     *
     * @param o Oferta
     */
    private void agregarALista(List<Oferta> l, Oferta o) {

        if (consultar(l, o.getCodigo())) {
            // Hacer nada.
        } else {
            l.add(o);
        }
    }

    private Clave eliminar(List<Oferta> l, String codigo) {
        Clave result = Clave.RESULT_OK;;

        if (consultar(l, codigo))
        {
            Oferta of = obtener(l, codigo);
            
            l.remove(of);
        } else
        {
            result = Clave.RESULT_NO_EXISTE;
        }

        return result;
    }

    private Oferta obtener(List<Oferta> l, String value) {
        Oferta oferta;

        oferta = null;

        for (Oferta of : l) {
            if (of.getCodigo().equals(value)) {
                oferta = of;
                break;
            }
        }
        return oferta;
    }

    private boolean consultar(List<Oferta> list, String codigo) {
        boolean band;

        band = false;

        for (Oferta of : list) {
            if (of.getCodigo().equals(codigo)) {
                band = true;
                break;
            }
        }

        return band;
    }

    //*************************** Formulario *********************
    /**
     * Carga la nueva lista en tabla.
     *
     * @param tabla
     * @param l
     */
    private void iniciarFormulario() {
        iniciarConfiguracion();
        mostrarListaEnTabla(tablaOfertas, copLOfertas);
    }

    private void mostrarListaEnTabla(JTable tabla, List<Oferta> l) {
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();

        for (int INDEX = 0; INDEX < l.size(); INDEX++) {
            Oferta of = l.get(INDEX);
            String p0 = of.getCodigo();
            String p1 = of.getDescripcion();
            String p2 = String.valueOf(of.getUnidOfert());
            String p3 = Utiles.formatear(of.getPrecioVenta());
            String[] datos = {p0, p1, p2, p3};

            model.insertRow(INDEX, datos);
        }
    }

    private void limpiarTabla(JTable tabla) {
        Utiles.limpiarTabla(tabla);
    }

    private void limpiarFormulario() {
        limpiarTablaOfertas();
    }

    private void limpiarTablaOfertas()
    {
        limpiarTabla(tablaOfertas);
    }
    
    private void actualizarForm() {
        Utiles.pararEdicion(tablaOfertas);
        limpiarTablaOfertas();
        mostrarListaEnTabla(tablaOfertas, copLOfertas);
    }
    
    private void iniciarConfiguracion()
    {
        DefaultTableModel model = (DefaultTableModel) tablaOfertas.getModel();

        model.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                if (e.getType() == TableModelEvent.UPDATE) {
                    try {
                        iniciarProc2();
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            }
            
  
        });
        
        Utiles.suprimirComilla(tablaOfertas);
    }
}
