package com.mycompany.libreria.gral.system.model;
// Generated 28/10/2020 01:10:07 by Hibernate Tools 4.3.1

/**
 * Codigo generated by hbm2java
 */
public class Codigo implements java.io.Serializable {

    private Integer id;
    private String codigo;
    private boolean estado;

    public Codigo() {
        this.id = -1;
        this.codigo = "";
        this.estado = false;
    }

    public Codigo(String codigo) {
        this.id = -1;
        this.codigo = codigo;
        this.estado = false;
    }

    public Codigo(Integer id, String codigo, boolean estado) {
        this.id = id;
        this.codigo = codigo;
        this.estado = estado;
    }


    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public boolean isEstado() {
        return estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    
}
