/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utiles;

/**
 *
 * @author CASA
 */
public enum Clave {
    RESULT_OK, RESULT_EXISTE, RESULT_NO_EXISTE, RESULT_EXITO, RESULT_EXITO_BD, RESULT_ERROR,
    RESULT_ERROR_BD, RESULT_ERROR_CAMPOS_INVALIDOS, RESULT_ERROR_CAMPO_INVALIDO,
    RESULT_SIN_DEFINIR, RESULT_OBJETO_EXISTENTE, RESULT_OBJETO_NUEVO, RESULT_CODIGO_REPETIDO, RESULT_MODIFICAR, RESULT_NUEVO,
    RESULT_ELIMINAR, RESULT_ERROR_SELECCION, RESULT_LISTA_VACIA, RESULT_ERROR_BD_ACTUALIZACION,
    RESULT_ERROR_IMPRESION, RESULT_CAMPO_BLANCO, RESULT_INCONSISTENCIA, RESULT_INICIO_FORMULARIO,
    RESULT_ACT_LISTA_ARCHIVO_DIF, MESSAGE_CONSULTA, RESULT_ENCONTRADOS, RESULT_HACER_NADA, RESULT_TODOS_CAMPOS_VACIOS, RESULT_SIN_CAMBIOS,
    RESULT_EXISTE_EN_LISTA, RESULT_NO_ENCONTRADO,
    FORM_GEN_CODIGO, RESULT_ERROR_PROGRAMA, MENSAJE_NUEVO_INVENTARIO, MENSAJE_MODIFICAR_INVENTARIO,
    NUEVA_SALIDA_REG_RAP, NUEVA_SALIDA_OFERTA, NUEVA_SALIDA_INVENTARIO
}
